services:
  nextjs:
    build:
      context: ./antidote_design
      dockerfile: Dockerfile
    container_name: nextjs
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - antidote-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "3030:80"
      - "8443:443"
    depends_on:
      - nextjs
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./.ssh:/etc/nginx/ssl:ro
    networks:
      - antidote-network

networks:
  antidote-network:
    driver: bridge